# Generated by Django 3.1.7 on 2021-03-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_recurrence',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_recurrence',
        ),
    ]
